language: node_js
node_js:
- '8'
dist: xenial
addons:
  ssh_known_hosts: 
    - secure: Ds6L3MYzFSB5NWrBhrf30SJKUt9UVX0VHbqiMQFF2QQT8yE0NdO35Gej285ZX4K36ZoBGICo1gCgcNWPVtdZ5uzDGHx2Ysa8hjeVrwqip2KIQiZ2YmBMZkrRH7UE5InKSS4vMxSmHUdzhWQjqbCQBHhn5UxPCYu+9qFmyBS9/ClErbBdQtR/w8mSAvKietHq9pu/lhylDEjS3KQc+XGuDgr48KKI+AmmaGrb2PzMUfoAcE0kDpP0+oQ4p7voLZ4F9FH5G/r5ru/Q5VxoDcYO4TMscgNy05J9k1cIwloPFxxDYSDO+ylWkOJKp3QtGZYx95spxOXbVEHeqny12jGZjBNQxFpVrlMRUU83aWVtnt/62u1NJVq1romBU0b+PuMNhicoAQbcoqrMnuskVLZLN0IEZJufGimLmDPEG+RgU3xUpuxSeBQPg/U4w77e9jcNkkugU+ZCurpLW93nBNrdmkipJ6ukkwz60fa2qwuCdzKsxSSkx15GGfnxJpb69RVXYrzly6EhOWbcAV7nrqTZz9kSig1eQUmWj02UTDHjpzDtcpJGVCvCzbfY85NzbwB1JmgMbh+mopndKR4cP1V1P2Zx10JiGm/w1pb9vQ/J6gcVk95ZPpb7W+zH6hoUgrFj4UPBq0AYvT/sHQ7e8Z5wLwEsdHosBTVj7EPp9MIdFVQ=
before_deploy:
  - openssl aes-256-cbc -K $encrypted_52c0b3e48ca4_key -iv $encrypted_52c0b3e48ca4_iv -in .travis/deploy-key.enc -out /tmp/deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy-key
  - ssh-add /tmp/deploy-key
deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: M/OFR3gUuTYT331f4vT1vf+sPxUHhDOvLQB1tbQ+RkjOsDJlkzDCmHUfw4riYqxArj0/oKEyBJDiQ2MgUE2pyxKB7+hFaXQ7qjtXW4Z7qCvmhte4F5G+xMH/ZEcDb1iM4xjBe4nKRLQX0kVZGeuBVUW0KHjHDEtwJqXjAfzUoxVQB7LuSmItGKSQEoo0gsZFj8hn+uxIxY8h3kTqzrqxK+a/k5dkZvwyIuk7s+2v580uFiR793HZkBecxryAvVc15SAK0WiBnisFuLQdeNpj4ZIB7Mafd2zrtNPpeUXIr9mL3lMZsjzRoq1AQsSk4bDqwxXA4/S+lfQIt6ek+yi5QXCGpmqGegd81bMaLFBCvQ+O/yh3jAAKhQVzraynLNbXDIDIlP3qAS4VImTkFmieAOV1Qa+T4CrX8kFF8Q4fUxgHSn4NbcxSPBMTmwdhbHTM0NsEU/rK5scNeqHOx5WUsMtnZvnyFCJ9Yj1n51LylgGFjEWUx2X03iU+WFwLXrTm6ctJQb0B2laOshGRoYxBNK++wQMSalnmT8tI1OSjRF5dSglOUcN9L4/vyFpFT4WcTz1y6fCBYEXfys5+ATGyfPN8woXOmIAu0SZEwOmGH07VDJnYF3pDNfJbUXjX/d2cwWLoMpFLiUb13OhgJaBm0h682P/oUVYDyrP70075Qto=
