language: node_js
node_js:
- '10'
- '11'
- '12'
dist: xenial
before_script:
    - cp src/config.sample.json src/config.json
branches:
  only:
    - master
    - develop
notifications:
  slack:
    rooms:
      secure: M/OFR3gUuTYT331f4vT1vf+sPxUHhDOvLQB1tbQ+RkjOsDJlkzDCmHUfw4riYqxArj0/oKEyBJDiQ2MgUE2pyxKB7+hFaXQ7qjtXW4Z7qCvmhte4F5G+xMH/ZEcDb1iM4xjBe4nKRLQX0kVZGeuBVUW0KHjHDEtwJqXjAfzUoxVQB7LuSmItGKSQEoo0gsZFj8hn+uxIxY8h3kTqzrqxK+a/k5dkZvwyIuk7s+2v580uFiR793HZkBecxryAvVc15SAK0WiBnisFuLQdeNpj4ZIB7Mafd2zrtNPpeUXIr9mL3lMZsjzRoq1AQsSk4bDqwxXA4/S+lfQIt6ek+yi5QXCGpmqGegd81bMaLFBCvQ+O/yh3jAAKhQVzraynLNbXDIDIlP3qAS4VImTkFmieAOV1Qa+T4CrX8kFF8Q4fUxgHSn4NbcxSPBMTmwdhbHTM0NsEU/rK5scNeqHOx5WUsMtnZvnyFCJ9Yj1n51LylgGFjEWUx2X03iU+WFwLXrTm6ctJQb0B2laOshGRoYxBNK++wQMSalnmT8tI1OSjRF5dSglOUcN9L4/vyFpFT4WcTz1y6fCBYEXfys5+ATGyfPN8woXOmIAu0SZEwOmGH07VDJnYF3pDNfJbUXjX/d2cwWLoMpFLiUb13OhgJaBm0h682P/oUVYDyrP70075Qto=
